global:
  message: Welcome to customer service dev environment!!
server:
  port: 8082
message: Hello from Dev!
spring:
  datasource:
     url: jdbc:mysql://localhost:3306/customer_master
     driver-class-name: com.mysql.cj.jdbc.Driver
     username: root
     password: 12345@shubham
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
